apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql2019-deployment
  labels:
    app: mssql2019-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql2019-db
  template:
    metadata:
      labels:
        app: mssql2019-db
    spec:
      nodeSelector:
        agentpool: akswin
      containers:
      - name: mssql2019-db
        image: crn52f71dc003.azurecr.io/mssql2017
        envFrom:
        - secretRef:
            name: myssql-secret
        resources:
          limits:
            cpu: 1
            memory: 4G
          requests:
            cpu: .1
            memory: 300M
        ports:
          - containerPort: 80
            name: other 
            protocol: TCP
          - containerPort: 8080
            name: wiremock
            protocol: TCP
          - containerPort: 1433
            name: mssql
            protocol: TCP

