# This is the workflow to setup the environment for Data Platform CI/CD pipelines

name: CI/CD Environment Setup

on:
  workflow_dispatch: 
    inputs:
      projectName:
        description: 'Project Name'     
        required: true
        default: 'db-cicd-with-github-actions'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: Setup Azure Environment
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Documentation: https://github.com/Azure/login#configure-azure-credentials
      # Next steps is to set up a service principal in Azure which has permission to set up its own resource group and resources within that resource group, but not mess with those that it has not set up.
      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZ_SP_CREDENTIALS}}
          enable-AzPSSession: true 

      # Documentation: https://github.com/marketplace/actions/azure-powershell-action
      - name: Run Azure PowerShell script
        uses: azure/powershell@v1
        with:
          inlineScript: |
            $projectName = $Env:projectName;
            ./envSetup/setup.ps1
          azPSVersion: '3.1.0'

