name: Test interpreting matrix variables in a deployment file

# Controls when the action will run. 
on:
  push:
    branches:
      - image-pipeline


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  job-1:
    name: interpreting matrix vars
    runs-on: windows-latest # Kubectl 1.20

    strategy:
      matrix: 
        mssqlversion: ["mssql2014", "mssql2016", "mssql2017", "mssql2019"]

    steps:
      - name: Checkout self
        uses: actions/checkout@v2
        with:
          path: cicd


      - name: use matrix vars
        id: use-vars
        shell: pwsh
        run: |
          
          Write-Host "✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ";
          Write-Host "";
          Write-Host ("mssqlversionString: {0}" -f "${{ matrix.mssqlversion }}"); 
          Write-Host "";
          Write-Host "✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ";
          Write-Host "";
          
          (Get-Content -Path .\cicd\aks\mssql.deployment.template.yml) -replace 'matrix.mssqlversion','${{ matrix.mssqlversion }}' > .\cicd\aks\${{ matrix.mssqlversion }}.deployment.yml

          Write-Host "✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ";
          Get-Content -Path .\cicd\aks\${{ matrix.mssqlversion }}.deployment.yml
          Write-Host "✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ";

