name: Test Stuff

# Controls when the action will run. 
on:
  workflow_dispatch: 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  job-1:
    name: set vars
    runs-on: windows-latest # Kubectl 1.20

    steps:
      - name: create vars
        id: create-vars
        shell: pwsh
        run: |
          Write-Host '::set-output name=mssqlversions::{"mssqlversion":["2017","2019"]}'
          
    ## echo "::set-output name=matrix::{\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}"
    
    outputs:
      mssqlversions: ${{ steps.create-vars.outputs.mssqlversions }}

  job-2:
    name: read vars
    needs: job-1
    runs-on: windows-latest # Kubectl 1.20

    strategy:
      matrix: ${{fromJson(needs.job-1.outputs.mssqlversions)}}

    steps:
      - name: print vars
        id: print-vars
        shell: pwsh
        run: |
          Write-Host "${{ matrix.mssqlversion }}"




