name: Test Stuff 2

# Controls when the action will run. 
on:
 push:
   branches:
     - breaking-thing-more

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  job-set-secret:
    runs-on:  windows-latest

    steps:
      - name: create secret
        id: create-secret
        shell: pwsh
        run: |
          # something goes here.

  job-1:
    name: set vars
    runs-on: windows-latest

    env:
      MS_SQL_VERSIONS: '["mssql2016"]'
      AZ_SERVICE_PRINCIPAL_CREDENTIALS: ${{ secrets.AZ_SP_CRED_TEST_20210123 }}

    steps:

      - name: create vars
        id: create-vars
        shell: pwsh
        run: |
          $msSqlVersionForMatrix = '{"mssqlversion":'+$env:MS_SQL_VERSIONS+'}';
          Write-Host ("msSqlVersionForMatrix: {0}" -f "$msSqlVersionForMatrix"); 
          Write-Host ("::set-output name=msSqlVersionForMatrix::{0}" -f "$msSqlVersionForMatrix"); 
          
    outputs:
      msSqlVersionForMatrix: ${{ steps.create-vars.outputs.msSqlVersionForMatrix }}

  job-2:
    name: read vars
    needs: job-1
    runs-on: windows-latest

    strategy:
      matrix: ${{fromJson(needs.job-1.outputs.msSqlVersionForMatrix)}}
 
    steps:
      - name: print vars
        id: print-vars
        shell: pwsh
        run: |
          Write-Host "${{ matrix.mssqlversion }}";



